spring.application.name=CargoFlow
server.port = 8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring-doc.swagger-ui.path=/docs


jwt.access-token.expiration.ms=900000
jwt.refresh-token.expiration.sec=2592000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0